### ISSUE TITLE
releases contain unnecessary __pycache__ folders

### ISSUE THREAD

**Issue by OlafHaag** [Gorgious56/asset_browser_utilities#42]
Hi! I noticed that there's a considerable file size difference between downloading the main branch and a zipped release.
It turns out that your releases unnecessarily contain compiled python files in the \_\_pycache\_\_ folders and some orphaned folders.

To me it seems as if the release was packed locally from a working space and then uploaded. You could consider using a github action to build the release directly from a clean version. This could look somewhat like the untested setup below.

```
name: Release Asset Browser Utilities

on:
  push:
    tags:
      - '*'

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Zip Release
        uses: TheDoctor0/zip-release@master
        with:
          path: './'
          filename: 'asset_browser_utilities.zip'
      - name: Get Version Info
        run: |
          echo GH ref: ${{ github.ref }}
          ver=$(echo ${{ github.ref }} | grep -oP "[0-9]+.[0-9]+.[0-9]+-?.*")
          echo Version: $ver
          echo "::set-output name=version::${ver}"
        id: version
      - name: Release
        if: ${{ !endsWith(steps.version.outputs.version, '-pre') }}
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          name: Asset Browser Utilities ${{ steps.version.outputs.version }}
          files: asset_browser_utilities.zip
          fail_on_unmatched_files: true
          draft: true
          prerelease: false
      - name: Pre-Release
        if: ${{ endsWith(steps.version.outputs.version, '-pre') }}$
        uses: softprops/action-gh-release@v1
        id: create_prerelease
        with:
          name: Asset Browser Utilities ${{ steps.version.outputs.version }}
          files: asset_browser_utilities.zip
          fail_on_unmatched_files: true
          draft: true
          prerelease: true
```
